apiVersion: v1
kind: Config
clusters:
  - name: shoot--hibernate--cand-test
    cluster:
      server: 'https://api.cand-test.hibernate.shoot.canary.k8s-hana.ondemand.com'
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQUxKaGc1bWVBVExyZnhPTTc2VU5ja0F3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBeU1qSXhNalEzTXpoYUZ3MHpNVEF5TWpJeApNalEzTXpoYU1CVXhFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURqVWthWUtLUmhxRFZENFZuZmlhZGlEWkEyS2JNSVkreVUvd2ZreEI4S1d2S2IKQlprZVNMamE2MVUyL1hDODJQd2dXbVhVeFVwSjJ2cFhLMWdsSnQxWVVvUGNGTk5mTFNCT29JUU5GZlFpMXU5agp3Z25PUGp6d01BWnlHVzBLYUlmSU5meklhb1VWZStFd3RJWnJ2dlluNjFHTVc3VkxGTzNZL0VJV0xWdDZoT2I5ClZFaVc4NElkRUEyRExXT0p3VTVZanVaZWIvalg1QUdxZ2ZUQ3k4cTJxQ3JES2g5aTNXNGZhZTUwU0FwSE9IR0sKT2JmOG03cUVCRHoyYS9GSVJRMnF1WUpPeXdINUswYllGVUtLVzBpME9BUWRPK0QyQVJNSCszMnpabWxlY01DQQpEbGQxaXNBTks0NHVDbytscElkR0tLdUNMU2FPWno2dDBlUzJVeVBaQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUOHVDeFE5dHh0Nmc2djVlQkIKcEdXUkFUa1pCVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBQklFc2Rwa2sxK2NPcWd3QXNMSlY3L2tQYktxQQo4eDFobTRjZllCS1VReC9OTC9XMEIyQThlWUFPcFBBNVVpQzBrU0xRVFVDT040dmdicFdLTTBvZHdyWTFKY1N5CjhyYXpYczBmSUg3czVrWmoxVjRnR0ZkQVpJSm91MzFkYWczUzdSVVIyNG9wRjBUemg5M0pFQ25WK0FrdVN5dTEKc2hMN251L2NNK29iem1zeUJGeGM4U1NsU3d4YmV2c3ZiaXBKczhzb0NXK0JBYWo4c2hneE9NdnVQME9HWndqWApMUHlaSW91a2w2SUYrNWRrV29rK25rNGo3MkRYRXJaYVZnNFVZSHVYeFF0ZzBGRUlUemQrbi9KbS9yMVF5M29uCnJoVmU1Nzc0SjMrL0dnZ0dLMTh5YjloUnMxTU1WS0xGbVNUNFJEdnpXRzNrQnpVY245WFVGdmdzV0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
contexts:
  - name: shoot--hibernate--cand-test
    context:
      cluster: shoot--hibernate--cand-test
      user: shoot--hibernate--cand-test-token
current-context: shoot--hibernate--cand-test
users:
  - name: shoot--hibernate--cand-test-token
    user:
      token: >-
        uSidD0Y7uyJokWsOC1NFlL3C0hWyOAxZRsOnqJopZBZgQHYEzPak85bYC8CULTdACNydjlgIUJAq55XNUZ03VpCZmowjXu09rhultrpq5XRuEqxXv6iLUNcMh2JnZeD0
